# Generated by Django 2.2.4 on 2019-08-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190818_0900'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ('word',)},
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
