# Generated by Django 2.2.4 on 2019-08-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190818_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=255, unique=True)),
                ('normalized', models.CharField(max_length=255)),
            ],
        ),
    ]
